### PR TITLE
Create tetragonal L1_0 lattice

### PR DESCRIPTION
**Pull request by jguenole**
In mode "--create", added possibility to create tetragonal L1_0 lattice. As it is tretragonal, this is the first cubic lattice of Atomsk that requires 2 lattice parameters.
The first commit of this pull request (tried) fix some bugs that broke the compilation.

### CODE REVIEW

**Comment by pierrehirel** [comment]
Thank you for this commit. I displaced some of your code so that it is located in the right place in the source code and in the documentation.

Best,
Pierre

**Comment by jguenole** [comment]
Great Pierre! Thanks for this faster-than-light merge! :)
Best,
Julien

**Comment by jguenole** [comment]
I realized that I didn't see the option "fct" to create "Face-centered tetragonal" and others before this pull request about L1_0... That's my bad to look at the Online documentation only :)
Feel free to remove the L1_0 option if you think it is useless in addition to the "fct" option.

Best,
Julien

**Comment by pierrehirel** [comment]
Ok, I didn't realize that L10 is basically the fct with 2 atomic species, which I had already implemented.
I'll delete your code (sorry for that!), but will keep the possibility to call the structure with "L1_0".

Best
Pierre

**Pull request merged**
